<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.apple.chain</groupId>
        <artifactId>apple-chain-platform</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>apple-module-trace</artifactId>
    <packaging>jar</packaging>
    <name>apple-module-trace</name>
    <description>Traceability module</description>

    <dependencies>
        <dependency>
            <groupId>com.apple.chain</groupId>
            <artifactId>apple-common</artifactId>
        </dependency>
        <dependency>
            <groupId>com.apple.chain</groupId>
            <artifactId>apple-module-chain</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.zxing</groupId>
            <artifactId>core</artifactId>
            <version>3.5.3</version>
        </dependency>
        <dependency>
            <groupId>com.google.zxing</groupId>
            <artifactId>javase</artifactId>
            <version>3.5.3</version>
        </dependency>
    </dependencies>
</project>
