-- =============================================================================
-- V19 - M7 Matching + Negotiation + Chat
--
-- Three tables:
--   td_trade_match       - candidate matches generated by the algorithm
--   td_trade_negotiation - bilateral price negotiations on top of a match
--   td_chat_message      - messages exchanged on a negotiation (or freeform)
--
-- Decisions:
--   1. UNIQUE (supply_id, demand_id) on td_trade_match prevents duplicate
--      candidates if the algorithm reruns; ON DUPLICATE updates the score.
--   2. td_chat_message uses string session_id (e.g. "negotiation-123") so
--      future channel types (user-DM) can reuse the same table.
--   3. msg_type allows TEXT / PRICE_OFFER / IMAGE / CONTRACT for forward
--      compatibility; only TEXT and PRICE_OFFER are emitted by M7.
-- =============================================================================

CREATE TABLE IF NOT EXISTS `td_trade_match` (
    `id`           BIGINT       NOT NULL,
    `supply_id`    BIGINT       NOT NULL,
    `demand_id`    BIGINT       NOT NULL,
    `match_score`  DECIMAL(5,2) NOT NULL,
    `match_time`   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `status`       TINYINT      NOT NULL DEFAULT 0 COMMENT '0=候选 1=已发起沟通 2=议价中 3=已成交 4=已拒绝',
    `create_time`  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time`  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `create_by`    VARCHAR(64),
    `deleted`      TINYINT      NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_supply_demand` (`supply_id`, `demand_id`),
    KEY `idx_supply_score` (`supply_id`, `match_score`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='M7 撮合候选';

CREATE TABLE IF NOT EXISTS `td_trade_negotiation` (
    `id`              BIGINT       NOT NULL,
    `match_id`        BIGINT       NOT NULL,
    `supply_user_id`  BIGINT       NOT NULL,
    `demand_user_id`  BIGINT       NOT NULL,
    `current_price`   DECIMAL(10,2),
    `current_quantity` DECIMAL(12,2),
    `last_offer_by`   BIGINT                COMMENT '上一次报价的用户id',
    `status`          TINYINT      NOT NULL DEFAULT 0 COMMENT '0=进行中 1=已达成 2=已取消',
    `create_time`     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time`     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `create_by`       VARCHAR(64),
    `deleted`         TINYINT      NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_match` (`match_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='M7 议价会话';

CREATE TABLE IF NOT EXISTS `td_chat_message` (
    `id`           BIGINT       NOT NULL,
    `session_id`   VARCHAR(64)  NOT NULL COMMENT 'negotiation-{id} 或 user-{a}-{b}',
    `from_user_id` BIGINT       NOT NULL,
    `to_user_id`   BIGINT       NOT NULL,
    `msg_type`     VARCHAR(16)  NOT NULL DEFAULT 'TEXT' COMMENT 'TEXT/PRICE_OFFER/IMAGE/CONTRACT',
    `content`      TEXT         NOT NULL,
    `send_time`    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `read_flag`    TINYINT      NOT NULL DEFAULT 0,
    `create_time`  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time`  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`      TINYINT      NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_session_time` (`session_id`, `send_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='M7 聊天消息';
